// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3N7iCFSVZtZIAXb0HXyDjr15wMasjb0I',
    appId: '1:726913974446:web:0e32fad679e4173ebded3f',
    messagingSenderId: '726913974446',
    projectId: 'apptarefa-6013e',
    authDomain: 'apptarefa-6013e.firebaseapp.com',
    storageBucket: 'apptarefa-6013e.firebasestorage.app',
    measurementId: 'G-DLX0Q4T24W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATTHeGwBI-byoAgzwhOdD2iPzJkzf5rfw',
    appId: '1:240027929027:android:cf228fb25c920115211576',
    messagingSenderId: '240027929027',
    projectId: 'apptarefas-fa234',
    storageBucket: 'apptarefas-fa234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOXM_LHoWCtwjP-VFmgrY3WmjPab5-9YI',
    appId: '1:726913974446:ios:d1bd67ff6e8eee1bbded3f',
    messagingSenderId: '726913974446',
    projectId: 'apptarefa-6013e',
    storageBucket: 'apptarefa-6013e.firebasestorage.app',
    iosBundleId: 'com.example.appRyan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOXM_LHoWCtwjP-VFmgrY3WmjPab5-9YI',
    appId: '1:726913974446:ios:d1bd67ff6e8eee1bbded3f',
    messagingSenderId: '726913974446',
    projectId: 'apptarefa-6013e',
    storageBucket: 'apptarefa-6013e.firebasestorage.app',
    iosBundleId: 'com.example.appRyan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3N7iCFSVZtZIAXb0HXyDjr15wMasjb0I',
    appId: '1:726913974446:web:5dfb53c444791980bded3f',
    messagingSenderId: '726913974446',
    projectId: 'apptarefa-6013e',
    authDomain: 'apptarefa-6013e.firebaseapp.com',
    storageBucket: 'apptarefa-6013e.firebasestorage.app',
    measurementId: 'G-RM0970893Z',
  );
}
